language: node_js
node_js:
    - "6"
install:
    - npm install
script:
    - npm test
after_script:
    - istanbul cover ./node_modules/mocha/bin/_mocha tests/**/*.test.js
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
